version: '3'
services:
  download-manager:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "5000:5000"
    # volumes:
    #   - path_to_data:./data
    #   - path_to_logs:./logs
    environment:
      - SECRET_KEY=your_secret_key