version: '3'
services:
  download-manager:
    restart: always
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - ~/Downloads:/app/downloader/downloads
      - /etc/localtime:/etc/localtime:ro
      - ~/Downloads/DownloadManager/data:/app/downloader/data
      - ~/Downloads/DownloadManager/logs:/app/downloader/logs
    environment:
      - SECRET_KEY=your_secret_key